### ISSUE TITLE
README links to broken hackage page

### ISSUE THREAD

**Issue by nilslice** [extism/haskell-sdk#15]
![image](https://github.com/extism/haskell-sdk/assets/7517515/d5e0077f-299d-4af0-b76e-08fcc03d13b8)

The note at the bottom of the README includes a broken link:

https://hackage.haskell.org/package/extism-0.5.0/docs/Extism-HostFunction.html

**Comment by zshipko** [comment]
This is only broken right now because `HostFunction` has a different name in the released version, once we make a new release the link should work.

**Comment by nilslice** [comment]
Ah, gotcha! Ok thanks 🙏
